name: update website

on: [workflow_dispatch]
 # schedule:
 #   - cron:  '35 01 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          TOKEN: ${{ secrets.ADMIN_LIST }}
        run: python script.py
        
      - name: update website source code
        run: python indexBuilder.py

      - name: switching from HTTPS to SSH
        run: git remote set-url origin git@github.com:schauhan-2/github-admin-portal.git ${{ secrets.ssh }}

      - name: check for changes
        run: git status

      - name: stage changed files
        run: git add .

      - name: commit changed files
        run: git commit -m "Action - update website"

      - name: fetch from main
        run: git fetch origin main

      - name: push code to main
        run: git push origin HEAD:main
        
          
